- name: Setup karabiner symlink
  ansible.builtin.file:
    src: '{{ DOTFILES_REPO }}/roles/karabiner/files'
    path: ~/.config/karabiner
    state: link

- name: Get all karabiner rules
  register: karabiner_rules
  ansible.builtin.find:
    paths: '{{ DOTFILES_REPO }}/roles/karabiner/files/rules/'

- name: Install karabiner config template
  ansible.builtin.template:
    src:  '{{ DOTFILES_REPO }}/roles/karabiner/templates/config.json.j2'
    dest: '{{ DOTFILES_REPO }}/roles/karabiner/files/karabiner.json'
