vscode_extensions:
  - be5invis.toml                             # toml syntax highlighting
  - bmalehorn.vscode-fish                     # fish syntax highlighting
  - coenraads.bracket-pair-colorizer-2        # colorizes matching brackets
  - donjayamanne.githistory                   # git log
  - dracula-theme.theme-dracula               # dracula theme
  - fabiospampinato.vscode-open-in-github     # open repo in github
  - hashicorp.terraform                       # terraform syntax highlighting
  - ionutvmi.path-autocomplete                # path completion
  - miguelsolorio.fluent-icons                # product icon theme
  - ms-python.python                          # support for python
  - ms-toolsai.jupyter                        # ms-python.python dependency
  - samuelcolvin.jinjahtml                    # jinja syntax highlighting
  - tabnine.tabnine-vscode                    # magical auto completion
